# config/config.yaml
genome_build: "hg19"          
input_vcf: "/home/faris/projects/annotation/input/TEST-1_CNV1.cnv.vcf" 
output_dir: "/home/faris/projects/annotation/FinalOUT/"             
classifycnv_script: "/home/faris/projects/annotation/ClassifyCNV/ClassifyCNV.py" 
annovar_dir: "/home/faris/projects/annotation/annovar/"  
merge_script: "/home/faris/projects/annotation/merge.py"
bed_script: "/home/faris/projects/annotation/vcf2bed.py"